# Done to increase the memory available to gradle.
org.gradle.jvmargs=-Xmx1G
# Fabric Properties
# check these on https://modmuss50.me/fabric.html
minecraft_version=1.21.11
yarn_mappings=1.21.11+build.4
loader_version=0.18.4
# Mod Properties
mod_version=0.1.1
maven_group=org.betterLostItems
archives_base_name=salts-anti-aliasing
# Dependencies
# check this on https://modmuss50.me/fabric.html
fabric_version=0.141.3+1.21.11
fabric_api_base_version=1.0.5+4ebb5c083e
fabric_lifecycle_events_version=2.6.15+4ebb5c083e
fabric_key_binding_version=1.1.7+4fc5413f3e
fabric_rendering_version=16.2.10+0290ad933e
fabric_data_generation_version=23.4.0+69974c4e3e
fabric_resource_loader_version=1.0.10+78c8b4663e
