package org.betterLostItems.salts_anti_aliasing.client.render.vulkan.fsr;

/**
 * Native AMD FSR dispatch arguments for one rendered frame.
 */
public record FsrEvaluateParameters(
        long commandBuffer,
        int fsrVersion,
        boolean frameGeneration,
        long inputColorImage,
        long inputColorView,
        long outputColorImage,
        long outputColorView,
        long depthImage,
        long depthView,
        long motionVectorImage,
        long motionVectorView,
        long opaqueColorImage,
        long opaqueColorView,
        long reactiveMaskImage,
        long reactiveMaskView,
        long transparencyMaskImage,
        long transparencyMaskView,
        long hudlessColorImage,
        long hudlessColorView,
        int renderWidth,
        int renderHeight,
        int outputWidth,
        int outputHeight,
        float jitterX,
        float jitterY,
        boolean resetHistory,
        long frameIndex,
        float motionVectorScaleX,
        float motionVectorScaleY,
        float sharpness,
        float frameTimeDeltaMs,
        float cameraNear,
        float cameraFar,
        float cameraFovY,
        float viewSpaceToMeters,
        float cameraPositionX,
        float cameraPositionY,
        float cameraPositionZ,
        float cameraUpX,
        float cameraUpY,
        float cameraUpZ,
        float cameraRightX,
        float cameraRightY,
        float cameraRightZ,
        float cameraForwardX,
        float cameraForwardY,
        float cameraForwardZ
) {
}
